# Generated by Django 3.2.9 on 2022-03-17 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryID', models.AutoField(primary_key=True, serialize=False)),
                ('Slug', models.SlugField(null=True, unique=True)),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('MagazineID', models.AutoField(primary_key=True, serialize=False)),
                ('Slug', models.SlugField(null=True, unique=True)),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=800)),
                ('Image', models.ImageField(blank=True, upload_to='magazine_images')),
                ('Date', models.DateField()),
                ('URL', models.URLField(blank=True)),
                ('Discount', models.CharField(max_length=10, null=True, unique=True)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('DiscountPrice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Categories', models.ManyToManyField(blank=True, to='magportal.Category')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Slug', models.SlugField(null=True, unique=True)),
                ('Membership', models.DateField(null=True)),
                ('MembershipID', models.IntegerField(null=True)),
                ('Favourites', models.ManyToManyField(blank=True, related_name='Favouriteuserprofile', to='magportal.Magazine')),
                ('UserAccount', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='Mags',
            field=models.ManyToManyField(blank=True, to='magportal.Magazine'),
        ),
    ]
